name: Docker Image CI

on:  
  workflow_dispatch:
    inputs:
      username:
        description: 'version of this branch'
        default: 'v1.6.1'
        required: true
        type: string
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/arm64,linux/amd64
        DOCKER_IMAGE=arcw/sgcc_electricity
        docker buildx build --platform linux/amd64,linux/arm64 -t arcw/sgcc_electricity --file Dockerfile-for-github-action .

        
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
          name: arcw/sgcc_electricity
          path: arcw/sgcc_electricity.tar

