name: Docker Image CI

on:  
  workflow_dispatch:
    inputs:
      username:
        description: 'version of this branch'
        default: 'v1.6.1'
        required: true
        type: string
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Build and push Docker image
      run: |
        docker build -t sgcc_electricity --file Dockerfile-for-github-action .

    
    - name: Save Docker image as tar
      run: |
        docker save -o sgcc_electricity.tar sgcc_electricity

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
          name: sgcc_electricity
          path: sgcc_electricity.tar

